[package]
name = "corrs"
version = "0.0.2"
authors = ["ATM <naik.atmaram@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
corr_server_lib={path="../lib/corr_server_lib"}
clap = "2.33.0"
toml = "0.5"