name: Dev Workflow - Test and check thing

on:
  push:
    branches:
      - dev

jobs:
  build:
    name: Test Commit
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:10.8
        env:
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
        ports:
          # will assign a random free host port
          - 5432/tcp
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v2
        with:
          ref: dev
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all
    outputs:
      job-status: ${{ job.status }}
  notify-slack:
    name: Notify on slack
    needs: build
    if: always()
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Slack Failure
        if: always()
        uses: kpritam/slack-job-status-action@v1
        with:
          job-status: ${{ needs.build.outputs.job-status }}
          slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
          channel: corr-health
