name: Dev Workflow - Test and check thing

on:
  push:
    branches:
      - dev

jobs:
  build:
    name: Build Binaries
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: dev
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all
    outputs:
      job-status: ${{ job.status }}
  notify:
  needs:
    - build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: exit 1
      - name: Slack Failure
        if: always()
        uses: kpritam/slack-job-status-action@v1
        with:
          job-status: ${{ needs.build.outputs.job-status }}
          slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
          channel: corr-health
