name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Publish Binaries
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release --all-features --package corr
    - name: Compress corr package
      uses: master-atul/tar-action@v1.0.2
      id: compress
      with:
        command: c
        cwd: target/release
        files: |
          corr
        outPath: corr.tar.gz
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: corr.tar.gz
        asset_name: corr.tar.gz
        tag: ${{ github.ref }}
        overwrite: true
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)
    - name: Update formula
      uses: mislav/bump-homebrew-formula-action@v1.6
      env:
        COMMITTER_TOKEN: ${{ secrets.COMMITTER_TOKEN }}
      if: "!contains(github.ref, '-')" # skip prereleases
      with:
        homebrew-tap: atmnk/homebrew-corr
        formula-name: corr
        download-url:  ${{format('{0}{1}{2}', 'https://github.com/atmnk/hwrust/releases/download/', steps.get_version.outputs.VERSION , '/corr.tar.gz')}}
        commit-message: 'Bump up {{formulaName}} formula to v{{version}} version'
